In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -2.5244e-29,  0.0000e+00],
        [-2.5244e-29,  5.6052e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 5.1268e+18,  2.0005e+00,  5.1464e+18]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4671, 0.9397, 0.4749],
        [0.5677, 0.5143, 0.8920],
        [0.6574, 0.0806, 0.9156],
        [0.4541, 0.1112, 0.3680],
        [0.7727, 0.3038, 0.1768]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [9]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[ 0.3434, -1.8936, -0.4220],
        [ 0.6260, -0.8256,  1.3581],
        [ 1.2114, -1.3407, -1.8384],
        [-0.5561, -1.9085,  0.8957],
        [ 0.7617, -0.3438,  1.7298]])


In [10]:
print(x.size())

torch.Size([5, 3])


In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.6056, -1.8209,  0.1320],
        [ 1.6112, -0.1502,  2.2683],
        [ 1.7563, -0.4549, -1.4886],
        [-0.4320, -1.4688,  0.9543],
        [ 0.8717, -0.1068,  2.5934]])


In [12]:
print(torch.add(x, y))


tensor([[ 0.6056, -1.8209,  0.1320],
        [ 1.6112, -0.1502,  2.2683],
        [ 1.7563, -0.4549, -1.4886],
        [-0.4320, -1.4688,  0.9543],
        [ 0.8717, -0.1068,  2.5934]])


In [13]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.6056, -1.8209,  0.1320],
        [ 1.6112, -0.1502,  2.2683],
        [ 1.7563, -0.4549, -1.4886],
        [-0.4320, -1.4688,  0.9543],
        [ 0.8717, -0.1068,  2.5934]])


In [14]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.6056, -1.8209,  0.1320],
        [ 1.6112, -0.1502,  2.2683],
        [ 1.7563, -0.4549, -1.4886],
        [-0.4320, -1.4688,  0.9543],
        [ 0.8717, -0.1068,  2.5934]])


In [15]:
print(x[:, 1])

tensor([-1.8936, -0.8256, -1.3407, -1.9085, -0.3438])


In [16]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.1009])
0.10091568529605865


In [19]:
# NUMPY BRIDGE
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [20]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [21]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[ 2.  2.  2.  2.  2.]


In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
